export const polishLocations = [
  { name: 'warszawa', postalCode: '00-001' },
  { name: 'kraków', postalCode: '30-001' },
  { name: 'gdańsk', postalCode: '80-001' },
  { name: 'wrocław', postalCode: '50-001' },
  { name: 'poznań', postalCode: '60-001' },
  { name: 'łódź', postalCode: '90-001' },
  { name: 'katowice', postalCode: '40-001' },
  { name: 'szczecin', postalCode: '70-001' },
  { name: 'bydgoszcz', postalCode: '85-001' },
  { name: 'lublin', postalCode: '20-001' },
  { name: 'białystok', postalCode: '15-001' },
  { name: 'ustrzyki dolne', postalCode: '38-700' },
  { name: 'zakopane', postalCode: '34-500' },
  { name: 'sopot', postalCode: '81-001' },
  { name: 'kielce', postalCode: '25-001' },
  { name: 'toruń', postalCode: '87-100' },
  { name: 'radom', postalCode: '26-600' },
  { name: 'rzeszów', postalCode: '35-001' },
  { name: 'płock', postalCode: '09-400' },
  { name: 'ełk', postalCode: '19-300' },
];

export const venueTypes = [
  'cozy cabin',
  'mountain lodge',
  'lakeside cottage',
  'forest retreat',
  'countryside villa',
  'enchanted hut',
  'rustic barn',
  'treehouse',
  'glamping tent',
  'tiny house',
  'stone cottage',
  'wooden chalet',
  'eco lodge',
  'boutique hideaway',
  'vintage cabin',
  'modern retreat',
  'traditional manor',
  'minimalist lodge',
  'artistic studio',
  'wellness center',
];

export const features = [
  'kitchen facilities',
  'bathroom facilities',
  'fireplace',
  'hypoallergic bedding',
  'speakers',
  'TV',
  'WiFi',
  'pet friendly',
  'parking',
  'lake and mountains nearby',
  'air conditioning',
  'heating',
  'washing machine',
  'dishwasher',
  'microwave',
  'coffee machine',
  'balcony',
  'terrace',
  'garden',
  'barbecue',
  'hot tub',
  'sauna',
  'gym',
  'pool',
  'bike rental',
  'kayak rental',
  'hiking trails',
  'ski storage',
  'game room',
  'library',
  'workspace',
  'printer',
  'safe',
];
